#!/bin/bash

# Input directory
if [ -z "$1" ]; then
    echo "Please provide input directory containing pdb files"
    exit 1
fi
input_dir=$(readlink -f $1)
if [ ! -d "$input_dir" ]; then
    echo "Input directory $input_dir does not exist"
    exit 1
fi
# Output file
if [ -z "$2" ]; then
    echo "Please provide output file"
    exit 1
fi
output_file=$2
output_dir=$(dirname $output_file)
mkdir -p $output_dir
output_dir=$(readlink -f $output_dir)
output_filename=$(basename $output_file)
# Additional arguments
additional_args=${@:3}


echo "Input directory: $input_dir"
echo "Output file: $output_file"


#full path
input_dir=$(readlink -f $input_dir)

# Run 
MOUNT_STR="-v $output_dir:/output -v $input_dir:/input"
GPU_STR="--runtime=nvidia -e NVIDIA_DRIVER_CAPABILITIES=compute,utility -e NVIDIA_VISIBLE_DEVICES=all"
docker run --rm $MOUNT_STR $GPU_STR daeseoklee/bsp-inference -i /input -o /output/$output_filename $additional_args
if [ -f $output_file ]; then
    echo "Output file $output_file is generated"
else
    echo "Output file $output_file is not generated"
    exit 1
fi
